### ISSUE TITLE
serialization error 2

### ISSUE THREAD

**Issue by brianfromoregon** [Lycoon/clash-api#22]
Ran across another serialization error

```
kotlinx.serialization.MissingFieldException: Field 'attacks' is required for type with serial name 'com.lycoon.clashapi.models.war.WarMember', but it was missing at path: $.opponent.members[5] at path: $.opponent.members[5] at path: $.opponent.members[5] at path: $.opponent.members[5]
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:90)
	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:95)
	at com.lycoon.clashapi.core.ClashAPI.getWarLeagueWar(ClashAPI.kt:419)
	at com.umpquatechnology.Main.clashCall(Main.java:115)
	at com.umpquatechnology.Main.main(Main.java:35)
Caused by: kotlinx.serialization.MissingFieldException: Field 'attacks' is required for type with serial name 'com.lycoon.clashapi.models.war.WarMember', but it was missing at path: $.opponent.members[5] at path: $.opponent.members[5] at path: $.opponent.members[5]
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:90)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeNullableSerializableElement(AbstractDecoder.kt:79)
	at com.lycoon.clashapi.models.war.War$$serializer.deserialize(War.kt:5)
	at com.lycoon.clashapi.models.war.War$$serializer.deserialize(War.kt:5)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70)
	... 4 more
Caused by: kotlinx.serialization.MissingFieldException: Field 'attacks' is required for type with serial name 'com.lycoon.clashapi.models.war.WarMember', but it was missing at path: $.opponent.members[5] at path: $.opponent.members[5]
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:90)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeNullableSerializableElement(AbstractDecoder.kt:79)
	at com.lycoon.clashapi.models.war.WarClan$$serializer.deserialize(WarClan.kt:6)
	at com.lycoon.clashapi.models.war.WarClan$$serializer.deserialize(WarClan.kt:6)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70)
	... 9 more
Caused by: kotlinx.serialization.MissingFieldException: Field 'attacks' is required for type with serial name 'com.lycoon.clashapi.models.war.WarMember', but it was missing at path: $.opponent.members[5]
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:90)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(StreamingJsonDecoder.kt:162)
	at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:533)
	at kotlinx.serialization.internal.CollectionLikeSerializer.readElement(CollectionSerializers.kt:80)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70)
	... 14 more
Caused by: kotlinx.serialization.MissingFieldException: Field 'attacks' is required for type with serial name 'com.lycoon.clashapi.models.war.WarMember', but it was missing
	at kotlinx.serialization.internal.PluginExceptionsKt.throwMissingFieldException(PluginExceptions.kt:20)
	at com.lycoon.clashapi.models.war.WarMember.<init>(WarMember.kt:5)
	at com.lycoon.clashapi.models.war.WarMember$$serializer.deserialize(WarMember.kt:5)
	at com.lycoon.clashapi.models.war.WarMember$$serializer.deserialize(WarMember.kt:5)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70)
	... 23 more
```

**Comment by Lycoon** [comment]
Thanks! Fixed in [3155a13](https://github.com/Lycoon/clash-api/commit/3155a130d7819014827ef6e2dde311fcf67a3881)
